networks:
  bbsvx-net:
    driver: bridge

services:
  bbsvx_root:
      hostname: bbsvx_root
      image: bbsvx:latest
      ports:
        - 2304
        - 10300
        - 8085
        - 9090
      environment:
        - TZ="Europe/Paris"
        - DOCKER_COMPOSE=true
        - BBSVX_NODE_NAME=bbsvx@bbsvx_root
        - BBSVX_COOKIE=bbsvx
        - BBSVX_BOOT=root
        - BBSVX_P2P_PORT=2304
        - BBSVX_HTTP_PORT=8085
      networks:
        - bbsvx-net
      volumes:
        - bbsvx_root_data:/bbsvx/data
        - bbsvx_root_logs:/bbsvx/logs
      command: >
        sh -c "
        mkdir -p /bbsvx/data /bbsvx/logs;
        /bbsvx/docker-start.sh
        "
      healthcheck:
        test: ["CMD", "/bbsvx/bin/bbsvx", "ping"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

  bbsvx_client:
      hostname: bbsvx_client
      image: bbsvx:latest
      ports:
        - 2304
        - 10300
        - 8085
        - 9090
      environment:
        - TZ="Europe/Paris"
        - DOCKER_COMPOSE=true
        - BBSVX_NODE_NAME=bbsvx@bbsvx_client
        - BBSVX_COOKIE=bbsvx
        - BBSVX_BOOT=join bbsvx_root 2304
        - BBSVX_P2P_PORT=2304
        - BBSVX_HTTP_PORT=8085
        - BBSVX_CONTACT_NODES=bbsvx@bbsvx_root
      networks:
        - bbsvx-net
      volumes:
        - bbsvx_client_data:/bbsvx/data
        - bbsvx_client_logs:/bbsvx/logs
      command: >
        sh -c "
        mkdir -p /bbsvx/data /bbsvx/logs;
        /bbsvx/docker-start.sh
        "
      healthcheck:
        test: ["CMD", "/bbsvx/bin/bbsvx", "ping"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
      depends_on:
        bbsvx_root:
          condition: service_healthy

volumes:
  bbsvx_root_data:
  bbsvx_root_logs:
  bbsvx_client_data:
  bbsvx_client_logs: