{
 "title": "Spray layer monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "container", "label": "Container", "query": { "query": "label_values(container_name)" } }
  ]
 },
 "panels": [
  {
   "title": "View Sizes",
   "type": "timeseries",
   "description": "Number of nodes in out and in view.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spray_inview_size_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spray_outview_size_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spray Exchange Timeout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "spray_initiator_echange_timeout_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Depleted Inviews",
   "type": "timeseries",
   "description": "Increase when inview size reach 0",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "spray_inview_depleted_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spray_outview_depleted_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spray Empty inview answered",
   "type": "timeseries",
   "description": "Increase when the node have answered and empty inview request",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "spray_empty_inview_answered_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum views",
   "type": "timeseries",
   "description": "Sum of all nodes views and inviews",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(container_name) (spray_outview_size_bbsvx_root{container_name=~\"$container\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "spray_inview_size_bbsvx_root{container_name=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}