server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /var/run/promtail/positions.yaml

clients:
  - url: http://loki_collector:3100/loki/api/v1/push



scrape_configs:
- job_name: containers
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: label
          values: ["logs_prom=true"]

  pipeline_stages:
    - docker: {}
    - static_labels:
        job: "promtail"
    - json:
        expressions:
          ts: ts
          level: level
          container_name: container_name
          log: log
    - labels:
        level:
    - timestamp:
        source: ts
        format: RFC3339Nano
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
