global:
  scrape_interval: 1s  # Default scrape interval
  external_labels:
      monitor: 'bbsvx'

scrape_configs:
  # Existing job: bbsvx_scrape
  - job_name: bbsvx_scrape
    scrape_interval: 1s  # Scrape every second for real-time updates
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: ["logging=grafana"]
    relabel_configs:
      - source_labels: [__meta_docker_port_private]
        regex: '10300'
        action: keep
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
      - source_labels: [__meta_docker_container_name]
        target_label: 'container_name'
